### ISSUE TITLE
Syntax error for *SET* statements

### ISSUE THREAD

**Issue by aarjan** [frigus02/typescript-sql-tagged-template-plugin#1]
According to [mysqljs/mysql](https://github.com/mysqljs/mysql) 

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.
```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```
But, i get this error message
`Failed to parse: syntax error at or near "SET".`    
when using this statement: `'INSERT INTO posts SET ?`

**Comment by aarjan** [comment]
I would love to send pull request, if you could guide me how to resolve this.

**Comment by joandvgv** [comment]
This is a late reply but for anybody interested only postgres syntax is supported as per #10
