### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by lishine** [frigus02/typescript-sql-tagged-template-plugin#12]
The plugin shows error when using with sql() function inside tagged sql of
https://github.com/porsager/postgres
I am not using scheme, just using the syntax highlighting.
How can I disable the plugin?

**Comment by frigus02** [comment]
Hi @lishine. I assume you're using the VS Code extension [SQL tagged template literals](https://marketplace.visualstudio.com/items?itemName=frigus02.vscode-sql-tagged-template-literals).

I tried to figure out if it's possible to load the plugin on demand (only if enabled in settings). However that doesn't seem possible. I'm now thinking it may be best to publish 2 different VS Code extensions:
- One with syntax highlighting only
- One with syntax highlighting and this plugin

Would this solve your issue?

**Comment by lishine** [comment]
Yes. But I don't want to burden you. Most of the SQL currently is one line
 . Even if it is not highlighted it is fine currently.
Eventually it would be cool to also format it.
Is there a solution to format SQL inside tagged strings?

**Comment by frigus02** [comment]
Oh, formatting would be amazing. I don't know of a good formatter for SQL in general in VS Code, yet. #4 tracks that.

**Comment by frigus02** [comment]
I just published https://marketplace.visualstudio.com/items?itemName=frigus02.vscode-sql-tagged-template-literals-syntax-only. It's using the exact same code for the syntax highlighting. But it doesn't include the TypeScript plugin. This should be good for almost any flavor of SQL now.
