### ISSUE TITLE
SQL Formatting on JS Files?

### ISSUE THREAD

**Issue by karlhorky** [frigus02/typescript-sql-tagged-template-plugin#17]
Hi @frigus02 👋 Hope things are going great for you!

If I try to format a JavaScript file using the `Format Document` command, the option "TypeScript and JavaScript Language Features" doesn't show up 😦

![Screen Shot 2020-12-03 at 13 31 54](https://user-images.githubusercontent.com/1935696/101018692-247f6180-356c-11eb-9fc0-01dbe27ba614.png)

Wonder how this formatter can be enabled for JS files... 🤔

**Comment by karlhorky** [comment]
Oops, my bad, it disables the `TypeScript and JavaScript Language Features` when this configuration is in the `settings.json`:

```json
"javascript.format.enable": false
```

Closing!

**Comment by frigus02** [comment]
Ah, nice find. And thanks for updating the issue.
