### ISSUE TITLE
How to use it with node-postgres

### ISSUE THREAD

**Issue by giacomorebonato** [frigus02/typescript-sql-tagged-template-plugin#2]
Hi, I'd really like to use this extension in my project where I use node-postgres in Visual Studio Code.
My queries look like this:

```js
const { rows } = await db.query(`SELECT * from products`)
```

Is it possible or can you point me out to the right configuration please?

**Comment by frigus02** [comment]
Hi @giacomorebonato, to use this library you need a tag function called `sql` for your template strings. If you want to use user into your queries, you probably want to pass a query object to [node-postgres](https://github.com/brianc/node-postgres), so the function could look like this:

```ts
export const sql = (
  strings: TemplateStringsArray,
  ...values: any[]
) => ({
  text: String.raw(strings, ...values.map((_, i) => `$${i + 1}`)),
  values
});
```

You then tag your query strings with this function, e.g.:

```ts
const { rows } = await db.query(sql`SELECT * from products`);
// value passed to db.query is { text: 'SELECT * from products', values: [] }

const getProductById = (id: string) =>
  db.query(sql`SELECT * from products WHERE id = ${id}`);
  // value passed to db.query is { text: 'SELECT * from products WHERE id = $1', values: [id] }
```

For this library it doesn't matter how your `sql` function looks like. It needs to be called `sql` and you need to tag your template literals with it. That should be enough for the library work.

**Comment by giacomorebonato** [comment]
Do you think that it would be possible to look also for a method called `query`?
Happy to contribute if you think that it's possible and a good thing.

**Comment by frigus02** [comment]
Sorry @giacomorebonato, I missed your question.

It might be a bit of work to make this plugin look for a function instead of a tagged template literal. The logic to find tagged template literals is provided by [typescript-template-language-service-decorator](https://www.npmjs.com/package/typescript-template-language-service-decorator).

However, if you find a way and want to contribute, I'm happy to accept a PR.

**Comment by giacomorebonato** [comment]
I'll take a look if I can contribute. Thanks for the answer :)
