### ISSUE TITLE
how to import sql-tag in typescript projects

### ISSUE THREAD

**Issue by saerdnaer** [frigus02/typescript-sql-tagged-template-plugin#29]
I could not find any docs on this, so:

What do I have to import from which library so I can use sql template literal stings? In my VSCode I always got an `Cannot find name 'sql'.ts(2304)` error :-(

![image](https://user-images.githubusercontent.com/40266/160881956-661bd2f5-91b3-4356-810e-3714348d1bb3.png)

I could not find the extra setting mentioned in the readme:
> Since formatting is done with the syntax server, it won't work unless you disable the "TypeScript > Tsserver: Use Separate Syntax Server" setting.

**Comment by frigus02** [comment]
The `sql` function is not provided. The plugin assumes you have such a function in your project already.

For example, if you use [pg](https://www.npmjs.com/package/pg) with [@types/pg](https://www.npmjs.com/package/@types/pg), then you might use the following function to create a query config object (based on the example in https://node-postgres.com/features/queries#query-config-object):

```ts
import {QueryConfig} from "pg";

function sql(strings: TemplateStringsArray, ...values: any[]): QueryConfig {
  return {
    text: String.raw(strings, ...values.map((_, i) => `$${i + 1}`)),
    values,
  };
}

const query = sql`INSERT INTO users(name, email) VALUES(${'brianc'}, ${'brian.m.carlson@gmail.com'})`;

console.log(await client.query(query));
```
