### ISSUE TITLE
How can you create dynamic SQL strings?

### ISSUE THREAD

**Issue by redbmk** [frigus02/typescript-sql-tagged-template-plugin#6]
I'd like to dynamically add where clauses in a SQL statement. I'm just using fake-tag to create a `sql` tag that I end up passing into knex:

```
import sql from 'fake-tag';
import knex from './db';

export const getUserNames = (userId?: number) => knex.raw(
  sql`
    select first_name, last_name
    from users
    ${userId ? 'where userId = ?' : ''}
  `,
  userId ? [userId] : []
);
```

This throws an error though:

> Failed to parse: syntax error at or near "$1"

**Comment by frigus02** [comment]
Yeah, that's an issue I thought about a while back. I can't think of an easy solution. At the moment all the plugin does is transform all template placeholders into SQL params. So your example becomes:

```sql
select first_name, last_name
from users
$1
```

Then this gets parsed by the Postgres query parser. Obviously this is not a valid query, which means you see the mentioned error.

Are you just using the plugin to get syntax highlighting at the moment? I might add an option to explicitly enable the query validation/parsing 🤔

**Comment by redbmk** [comment]
I ended up switching to another plugin called "Inline SQL" for now which just does syntax highlighting, but I really like the idea of enabling query validation as well. As far as converting template placeholders to SQL placeholders, I wouldn't trust just typescript to avoid sql injection (maybe I have a REST API and I tell typescript to expect a `number` but in reality it could be a `string`?). Normally I would use something like sequelize or knex or just manually enter `?`s to make sure I'm using bind params, so even though this plugin should catch issues with SQL injection I personally would want that extra layer of protection that bind params gives, which means I would (in theory) never put a number in there directly (like the `where user_id = ${userId}` example). In fact, having an option in here that would look out for instances like that would be pretty nice.

Does this connect to the database and rely on that to do data validation, or is it done purely in typescript based on knowing the database schema?

I wonder if there would be a way to still do query validation by converting the template literal into a string and then validating against that. Since this is done in compile time though you might have to try it against every possible branch, which doesn't really seem feasible (at the very least not easy and probably an expensive operation).

The other issue is if you have sql fragments. I might have a couple CTEs that could be broken in to separate variables, so if the table doesn't exist in the database schema that wouldn't work outside of the full context. For example:

```
const cte1 = sql`
  select * from a where b = c;
`

const cte2 = sql`
  select * from d where e = f;
`

const fullQuery = sql`
  with g as (${cte1}), h as (${cte2})
  select * from g inner join h on (i = j)
  where k = l;
```

**Comment by frigus02** [comment]
I would love to support fragments of SQL queries. However it seems super complicated to put those together to a full query just using the type information from TypeScript.

I'm going to close this for now, because I don't think I will ever implement this.
